### ISSUE TITLE
Add a getwork-esque RPC (perhaps taking a webhook?)

### ISSUE THREAD

**Issue by EyeOfPython** [LogosFoundation/lotusd#42]
With the new header, `getblocktemplate` is overkill because sending all txs in a block is both unnecessary and inefficient.

Instead, we can just send the blockheader (+extended metadata), and let the miners do their thing.

A webhook might be an idea so miners immediately get informed of new headers when txs (i.e. merkle root) or blocks (i.e. prev block hash) changes, without having to continuously poll the thing.

**Comment by schancel** [comment]
I like the webhook idea. It will need a bit of infrastructure. Do we have a convenient API for making async http calls? We also need an internal queue for these events so we can fire off various things like webhooks and replay them if they fail.

As an aside, the existing ZMQ interface can be used for some things -- but it drops frequently and has no way to replay events. Additionally, it doesn't notify of certain types of things like mempool evictions. @hlb8122 tried to write an indexer, and uses it for some things in the cashweb stack. However, it is causing us problems.

**Comment by schancel** [comment]
Completed minimal api to satisfy this requirement.
