### ISSUE TITLE
Update cashd repo 'About' description please

### ISSUE THREAD

**Issue by ftrader** [LogosFoundation/lotusd#72]
Change the repo description please.

This software is no longer a "Bitcoin Cash" daemon.

**Comment by EyeOfPython** [comment]
Way more than that has to be changed, but this is one of them.

**Comment by schancel** [comment]
Hey @ftrader I'm excited that you've decided to participate. Thanks for pointing this out. There's a lot to do before launch.

I'd love it if you continued to help!
